//! `smelt init` — generate a skeleton job manifest.

use clap::Args;

/// Arguments for the `init` subcommand.
///
/// No fields — the output path is always `./job-manifest.toml`.
#[derive(Debug, Args)]
pub struct InitArgs {}

/// Skeleton job manifest written by `smelt init`.
///
/// Written as a raw string literal so that inline `#`-comments are preserved.
/// `toml::to_string_pretty()` strips comments, making struct serialization
/// unsuitable for this purpose (D065).
const SKELETON: &str = r#"# Smelt job manifest — generated by `smelt init`
#
# Edit this file, then run: smelt run job-manifest.toml --dry-run

[job]
# Human-readable name for this job (used in status and run directories).
name = "my-job"

# Repository to work on. Use "." for --dry-run; set an absolute path for real runs.
repo = "."

# Branch or commit to start from. Sessions branch off this ref.
base_ref = "main"

[environment]
# Container runtime — currently only "docker" is supported.
runtime = "docker"

# Docker image to use for all sessions.
image = "ubuntu:22.04"

# Optional resource limits.
# [environment.resources]
# cpu = "2"
# memory = "4G"

[credentials]
# LLM provider name (e.g. "anthropic", "openai").
provider = "anthropic"

# Model identifier. Check your provider's documentation for available models.
model = "claude-sonnet-4-20250514"

# Optional: override which environment variable holds the API key.
# [credentials.env]
# api_key = "ANTHROPIC_API_KEY"

[[session]]
# Unique name for this session. Referenced by depends_on and merge.order.
name = "implement"

# Task prompt given to the LLM agent running in this session.
spec = "Implement the feature described in TASK.md following the existing code style."

# Shell command run inside the container to verify the session's work.
harness = "cargo test"

# Maximum runtime in seconds before the session is forcibly stopped.
timeout = 600

# Optional: list sessions this session depends on.
# depends_on = ["other-session"]

[merge]
# How to combine results from multiple sessions.
# "sequential" applies changes one session at a time in order.
strategy = "sequential"

# Ordered list of session names to merge. Must reference valid session names.
# Leave empty to merge in definition order.
order = ["implement"]

# Branch to merge the combined result into.
target = "main"

# Optional: enable AI-assisted conflict resolution during merge.
# ai_resolution = true
"#;

/// Execute `smelt init`.
///
/// Writes `./job-manifest.toml` in the current directory. Exits 1 if the
/// file already exists (idempotency guard).
pub async fn execute(_args: &InitArgs) -> anyhow::Result<i32> {
    let dest = std::path::Path::new("job-manifest.toml");

    if dest.exists() {
        eprintln!(
            "Error: job-manifest.toml already exists. \
             Remove it first or edit it directly."
        );
        return Ok(1);
    }

    std::fs::write(dest, SKELETON)?;

    println!("Created job-manifest.toml — edit and run with: smelt run job-manifest.toml");

    Ok(0)
}

#[cfg(test)]
#[allow(clippy::await_holding_lock)] // CWD_LOCK guards process-global set_current_dir; these tests run serialized
mod tests {
    use super::*;
    use std::sync::Mutex;
    use tempfile::TempDir;

    // set_current_dir() is process-global; serialize all tests that use it.
    static CWD_LOCK: Mutex<()> = Mutex::new(());

    fn make_args() -> InitArgs {
        InitArgs {}
    }

    #[tokio::test]
    async fn test_init_creates_manifest() {
        let _guard = CWD_LOCK.lock().unwrap();
        let dir = TempDir::new().unwrap();
        std::env::set_current_dir(dir.path()).unwrap();

        let result = execute(&make_args()).await.unwrap();
        assert_eq!(result, 0, "execute() should return 0 on success");

        let manifest_path = dir.path().join("job-manifest.toml");
        assert!(
            manifest_path.exists(),
            "job-manifest.toml should be created"
        );

        let manifest = smelt_core::manifest::JobManifest::load(&manifest_path)
            .expect("manifest should load without error");
        manifest
            .validate()
            .expect("manifest should pass validate()");
    }

    #[tokio::test]
    async fn test_init_fails_if_file_exists() {
        let _guard = CWD_LOCK.lock().unwrap();
        let dir = TempDir::new().unwrap();
        std::env::set_current_dir(dir.path()).unwrap();

        std::fs::write(dir.path().join("job-manifest.toml"), b"# existing").unwrap();

        let result = execute(&make_args()).await.unwrap();
        assert_eq!(
            result, 1,
            "execute() should return 1 when file already exists"
        );
    }

    #[test]
    fn test_init_skeleton_parses() {
        let manifest: smelt_core::manifest::JobManifest =
            toml::from_str(SKELETON).expect("SKELETON must be valid TOML and parse correctly");
        manifest.validate().expect("SKELETON must pass validate()");
    }
}
